services:
  - type: web
    name: retail-ai-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: uvicorn backend.app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: SUPABASE_DB_HOST
        value: db.pdbybnpspykpdswotygx.supabase.co
      - key: SUPABASE_DB_PORT
        value: "5432"
      - key: SUPABASE_DB_USER
        value: postgres
      - key: SUPABASE_DB_PASSWORD
        value: MhRphDuLyqYr3CVC
      - key: SUPABASE_DB_NAME
        value: postgres
      - key: SUPABASE_URL
        value: https://pdbybnpspykpdswotygx.supabase.co
      - key: SUPABASE_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBkYnlibnBzcHlrcGRzd290eWd4Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc4NzIwNjYxOSwiZXhwIjoyMTAyNzgyNjE5fQ.-0TKFFNhF4pEsAoHRv886nl4aaNtcTthzrgn_cz_iTQ
      - key: SUPABASE_STORAGE_BUCKET
        value: reports
      - key: CORS_ORIGINS
        value: http://localhost:5173,https://retail-backend.netlify.app
